# render.yaml
services:
  - type: web
    name: departemen-app
    runtime: docker
    env: docker
    buildCommand: docker build -t departemen-app .
    startCommand: php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
    plan: free